name: CI/CD Pipeline

on:  
  push:
    branches: ["feature/*","develop","main","hotfix/*"]
  pull_request:
    branches: ["feature/*","develop","main","hotfix/*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set working directory
      run: cd D:/a/smart-charger-web/Software/smart-charger

    - name: List files in directory
      run: dir

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

   # - name: Set working directory
   #   run: cd Software/smart-charger
      
    - name: Install dependencies
      run: npm install #--prefix Software/smart-charger

    - name: Build
      run: npm run build #--prefix Software/smart-charger

    #- name: Test
    #  run: npm run test #--prefix Software/smart-charger

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
